#include "gtest/gtest.h"
#include "Vpcreg.h"           // Generated by Verilator
#include "verilated.h"
#include "verilated_vcd_c.h"

// Global pointers (same style as before)
Vpcreg *top;
VerilatedVcdC *tfp;
unsigned long tickcount = 0;

// Simple rising-edge tick (matches your ALU/regfile TB)
void tick() {
    top->eval();
    tfp->dump(tickcount++);
    top->clk = !top->clk;
    top->eval();
    tfp->dump(tickcount++);
    top->clk = !top->clk;
}

// ------------------ FIXTURE ------------------

class PCRegTest : public ::testing::Test {
protected:
    void SetUp() override {
        top->clk = 0;
        top->rst = 0;
        top->d   = 0;
        tick();
    }

    void TearDown() override {}
};

// ------------------ TEST CASES ------------------

// Reset forces q = 0
TEST_F(PCRegTest, ResetClearsPC) {
    top->d   = 1234;
    top->rst = 1;
    tick();
    EXPECT_EQ(top->q, 0u);

    top->rst = 0;
    tick();    // ensure reset is released cleanly
}

// q only updates on rising edge
TEST_F(PCRegTest, UpdatesOnlyOnClockEdge) {
    top->rst = 0;

    // Present a value but do not tick yet
    top->d = 100;
    top->eval();
    EXPECT_NE(top->q, 100u);    // must NOT update yet

    // Tick once → update occurs
    tick();
    EXPECT_EQ(top->q, 100u);
}

// Multiple sequential updates
TEST_F(PCRegTest, SequentialCounting) {
    top->rst = 0;

    int pc = 0;

    // Simulate PC + 4 increments
    for (int i = 0; i < 5; i++) {
        pc = pc + 4;
        top->d = pc;
        tick();
        EXPECT_EQ(top->q, (uint32_t)pc);
    }
}

// Reset in the middle of execution
TEST_F(PCRegTest, MidRunReset) {
    top->rst = 0;
    top->d   = 500;
    tick();
    EXPECT_EQ(top->q, 500u);

    top->rst = 1;
    tick();
    EXPECT_EQ(top->q, 0u);
}

// ------------------ MAIN ------------------

int main(int argc, char **argv) {
    Verilated::commandArgs(argc, argv);

    top = new Vpcreg;
    tfp = new VerilatedVcdC;

    Verilated::traceEverOn(true);
    top->trace(tfp, 99);
    tfp->open("pcreg.vcd");

    testing::InitGoogleTest(&argc, argv);
    int result = RUN_ALL_TESTS();

    top->final();
    tfp->close();
    delete top;
    delete tfp;

    return result;
}
